[build]
command = "npm run build"
publish = "build/client"

[dev]
command = "npm run dev"

[functions]
directory = ".netlify/functions-internal"
node_bundler = "esbuild"
included_files = ["build/server/**"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/remix-server"
status = 200
force = true

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
